#!/bin/bash
# /etc/init.d/4glte

### BEGIN INIT INFO
# Provides:noip
# Required-Start:$remote_fs $syslog
# Required-Stop:$remote_fs $syslog
# Default-Start:2 3 4 5
# Default-Stop:0 1 6
# Short-Description:Connect 4glte usb modem on boot
# Description:Connect 4glte usb modem on boot
### END INIT INFO

case "$1" in
  start)
    sleep 10
    # run application we want to start
    /home/pi/usb-modeswitch-data/4glte
    ;;
  stop)
    /home/pi/usb-modeswitch-data/4glte disconnect
    ;;
  *)
    echo "Usage: /etc/init.d/4glte {start|stop}"
    exit 1
    ;;
esac

exit 0
#*******************************************************

